### ISSUE TITLE
Package not working on linux

### ISSUE THREAD

**Issue by Polve** [Bitcoin-com/wormholecash#1]
I followed instructions and globally installed wormholecash (v. 3.0.0) in my system but when trying to run it I get this error:

$ wormhole
module.js:538
    throw err;
    ^

Error: Cannot find module './lib/wormhole'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dusty/.nvm/versions/node/v8.9.3/lib/node_modules/wormholecash/index.js:16:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

I don't see a "wormhole" file, but I find one named "Wormhole" (with the first capital letter), maybe you developed on a system that does not check cases, like windows?

**Comment by Polve** [comment]
In fact, renaming Wormhole.js to wormhole.js makes the program start correctly.

Otherwise you can change that line in index.js, from
> let Wormhole = require('./lib/wormhole').default;
to
> let Wormhole = require('./lib/Wormhole').default;

**Comment by cgcardona** [comment]
Thanks for spotting this. Fixed here https://github.com/Bitcoin-com/wormholecash/commit/61eb99a90f1850fa26809a80f22c6e5d899e49e3#diff-168726dbe96b3ce427e7fedce31bb0bcR16

@gitcash tip $1 to @Polve
