### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/wormholecash#4]
When I was working through [the third tutorial](https://developer.bitcoin.com/tutorials/wormhole-3-tokens.html) and developing [these test scripts](https://github.com/christroutner/bch-tests), the majority of the errors I hit did not appear to be handled correctly by the Wormhole libraries. Here is a typical example of what I'm talking about:

Making a simple example call like this:
```
wormhole.DataRetrieval.info().then(
  result => {
    console.log(result);
  },
  err => {
    console.log(err);
  }
);
```
Results in an error message like this:
```
TypeError: Cannot read property 'data' of undefined
    at DataRetrieval.info (/home/trout/work/bch/bch-tests/node_modules/wormholecash/lib/DataRetrieval.js:111:46)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

When you look up [Line 111](https://github.com/Bitcoin-com/wormholecash/blob/master/lib/DataRetrieval.js#L111) you can see that the error is generated by the *error hander*, not the actual error.

There are a lot of different ways to handle errors like this, but since this is a library, I think a simple `throw error;` may be best. The current way of handling errors is really self defeating since the error handler is masking the real error. This would really stump a novice developer. 

Replacing 
`return JSON.stringify(error.response.data.error.message);`
with
`throw error;`
results in...

```
{ Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000,
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.17.1' },
     method: 'get',
     url: 'http://localhost:3000/v1/dataRetrieval/info',
     data: undefined },
  request: 
   Writable {
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events: 
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options: 
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        hostname: 'localhost',
        port: '3000',
        path: '/v1/dataRetrieval/info',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        nativeProtocols: [Object],
        pathname: '/v1/dataRetrieval/info' },
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /v1/dataRetrieval/info HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.17.1\r\nHost: localhost:3000\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/v1/dataRetrieval/info',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://localhost:3000/v1/dataRetrieval/info' },
  response: undefined }
```
...which is a much more informative error.

If replacing these kinds of error handlers with a simple `throw error;` sounds appropriate, I'd be happy to work to submit a pull request.

**Comment by christroutner** [comment]
I've used two different assertion libraries to test thrown errors. [ava](https://github.com/avajs/ava#throwsfn-expected-message) and [chai](http://www.chaijs.com/api/assert/#method_throws) both have `.throws` assertions. I'm personally a fan of Mocha/Chai, but ava is a solid quality test runner too. The main difference is that ava runs in parallel, but I'm a purist and believe that tests should be run sequentially for clarity; hence my Mocha preference.

For an integration test, the next step is reliability getting the function to thow an error. It would be good to have coverage for different error scenarios, like 1) ECONNREFUSED and 2) HTTP 503 and 3) A rejected promise. There are probably other things that could throw an error too.

The library functions are pretty simple for a unit test, but if you wanted them for coverage, you could mock axios and force a throw. For mocking, you could use [sinon](https://sinonjs.org/) or [mockery](https://github.com/mfncooper/mockery)

**Comment by christroutner** [comment]
In particular, you'd want to use [sinon.stub()](https://sinonjs.org/releases/v6.1.5/stubs) method. I'll try to add an example tonight, combining a format similar to the mocha tests for this project and using `sinon.stub()` to mock out axios.

**Comment by christroutner** [comment]
Here is a gist I just created to illustrate some additional testing ideas:

https://gist.github.com/christroutner/486155ff99da7fb395026cc08e41b2e6

**Comment by christroutner** [comment]
Also thought I'd mention that axios created [moxios](https://github.com/axios/moxios) for mocking axios for unit tests.

It may be difficult to simulate non-http errors with nock. Moxios is probably a more full featured way to mock for unit tests in this regard.
